sudo: required
dist: xenial
language: generic
install: git clone https://github.com/QubesOS/qubes-builder ~/qubes-builder
script: ~/qubes-builder/scripts/travis-build
env:
 - DISTS_VM=centos7 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1

# don't build tags which are meant for code signing only
branches:
  except:
    - /.*_.*/
    - build
